name: Notify Netlify

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
  release:
    types:
      - published

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build
        run: curl -s -X POST ${{ secrets.NETLIFY_BUILD_HOOK }}
